=== TiagoCabrera/employer/src/main/api/Schemas/Employee_Info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="First_name" />
										<xs:element type="xs:string" name="Last_name"
											minOccurs="0" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:int" name="Emp_ID" />
							<xs:element type="xs:byte" name="Age" />
							<xs:element name="Address">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="Street" />
										<xs:element type="xs:string" name="Area" minOccurs="0" />
										<xs:element type="xs:string" name="City" />
										<xs:element type="xs:string" name="State" />
										<xs:element type="xs:int" name="Pin_Code" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:float" name="Salary" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== TiagoCabrera/employer/src/main/api/Examples/Employee_Info.xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Employee_Info.xsd">
	<Employee>
		<Name>
			<First_name>Raghav</First_name>
			<Last_name>hegde</Last_name>
		</Name>
		<Emp_ID>1338482</Emp_ID>
		<Age>23</Age>
		<Address>
			<Street>Shanavalli</Street>
			<Area>Bedsgoan</Area>
			<City>Mundgod</City>
			<State>Karnataka</State>
			<Pin_Code>581346</Pin_Code>
		</Address>
		<Salary>25000</Salary>
	</Employee>
</Employees>
